import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import ToasterProvider from "@/components/ToasterProvider";

const noto = Noto_Serif_Bengali({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${noto.className}  h-full antialiased`}
    >
    <body className="min-h-full flex flex-col">
  <Header />
  <ToasterProvider />
  {children}
</body>
    </html>
  );
}
